apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gksr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rhka-tenant/rhtap-demo-app/hacbs-test-project-gksr@sha256:2db1124a54852d35cfe8946fec924626ac6b93d0984a049e6c5775954fd957b6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
